import json
import os

DIR = "C:/Users/luizd/.gemini/antigravity/scratch/anime-music-quiz"
SONGS_PATH = os.path.join(DIR, "anime_songs_verified.json")
OUT_PATH = os.path.join(DIR, "tools", "anime_autocomplete_db.json")

with open(SONGS_PATH, "r", encoding="utf-8") as f:
    songs = json.load(f)

# Base list from our quiz
base_titles = set()
for s in songs:
    base_titles.add(s["anime"])
    # Clean titles without parentheses
    clean = s["anime"].split("(")[0].strip()
    if clean:
        base_titles.add(clean)
    for syn in s.get("synonyms", []):
        if len(syn) > 2:
            base_titles.add(syn.title())

# 400+ Additional popular anime titles across all genres & eras, including franchise variants!
extra_anime = [
    # Fate Series (Multiple specific options as requested!)
    "Fate/stay night",
    "Fate/Zero",
    "Fate/stay night: Unlimited Blade Works",
    "Fate/stay night: Heaven's Feel",
    "Fate/Apocrypha",
    "Fate/Grand Order: Absolute Demonic Front - Babylonia",
    "Fate/Grand Order: First Order",
    "Fate/EXTRA Last Encore",
    "Fate/kaleid liner PRISMA ILLYA",
    "Fate/strange Fake",
    "Carnival Phantasm",

    # Naruto & Ninja
    "Naruto",
    "Naruto Shippuden",
    "Boruto: Naruto Next Generations",
    "Boruto: Two Blue Vortex",
    "Ninja Scroll",
    "Basilisk: Kouga Ninpou Chou",
    "Nabari no Ou",

    # Dragon Ball
    "Dragon Ball",
    "Dragon Ball Z",
    "Dragon Ball GT",
    "Dragon Ball Super",
    "Dragon Ball Daima",

    # Bleach
    "Bleach",
    "Bleach: Thousand-Year Blood War",
    "Burn the Witch",

    # One Piece
    "One Piece",
    "One Piece Film: Red",

    # Attack on Titan
    "Attack on Titan (Shingeki no Kyojin)",
    "Attack on Titan Season 2",
    "Attack on Titan Season 3",
    "Attack on Titan: The Final Season",
    "Attack on Titan: Junior High",

    # Shounen & Battle
    "Hunter x Hunter (2011)",
    "Hunter x Hunter (1999)",
    "Fullmetal Alchemist",
    "Fullmetal Alchemist: Brotherhood",
    "Yu Yu Hakusho",
    "Rurouni Kenshin",
    "InuYasha",
    "InuYasha: The Final Act",
    "Yashahime: Princess Half-Demon",
    "Shaman King",
    "Shaman King (2021)",
    "Soul Eater",
    "Soul Eater Not!",
    "Fire Force (Enen no Shouboutai)",
    "Fire Force Season 2",
    "Black Clover",
    "Fairy Tail",
    "Fairy Tail: 100 Years Quest",
    "Edens Zero",
    "Rave Master",
    "Seven Deadly Sins (Nanatsu no Taizai)",
    "Four Knights of the Apocalypse",
    "Magi: The Labyrinth of Magic",
    "Magi: The Kingdom of Magic",
    "The Heroic Legend of Arslan",
    "World Trigger",
    "Katekyo Hitman Reborn!",
    "D.Gray-man",
    "D.Gray-man Hallow",
    "Beelzebub",
    "Toriko",
    "Gintama",
    "Gintama'",
    "Gintama°",
    "Gintama: The Final",
    "Bungo Stray Dogs",
    "Blood Blockade Battlefront (Kekkai Sensen)",
    "Kekkai Sensen & Beyond",
    "Noragami",
    "Noragami Aragoto",
    "Twin Star Exorcists (Sousei no Onmyouji)",
    "Blue Exorcist (Ao no Exorcist)",
    "Blue Exorcist: Kyoto Saga",
    "Blue Exorcist: Shimane Illuminati Saga",
    "Kemono Jihen",
    "Chainsaw Man",
    "Jujutsu Kaisen",
    "Jujutsu Kaisen 0",
    "Jujutsu Kaisen Season 2 (Shibuya)",
    "Demon Slayer (Kimetsu no Yaiba)",
    "Demon Slayer: Mugen Train",
    "Demon Slayer: Entertainment District Arc",
    "Demon Slayer: Swordsmith Village Arc",
    "Demon Slayer: Hashira Training Arc",
    "My Hero Academia (Boku no Hero Academia)",
    "My Hero Academia Season 2",
    "My Hero Academia Season 3",
    "My Hero Academia Season 4",
    "My Hero Academia Season 5",
    "My Hero Academia Season 6",
    "My Hero Academia Season 7",
    "Dr. Stone",
    "Dr. Stone: Stone Wars",
    "Dr. Stone: New World",
    "Tokyo Revengers",
    "Tokyo Revengers: Christmas Showdown",
    "Tokyo Revengers: Tenjiku Arc",
    "Wind Breaker",
    "Kaiju No. 8",
    "Solo Leveling",
    "Dandadan",
    "Mashle: Magic and Muscles",
    "Mashle: Magic and Muscles S2",
    "Undead Unluck",
    "Shangri-La Frontier",
    "Hell's Paradise (Jigokuraku)",

    # Isekai & Fantasy
    "Sword Art Online",
    "Sword Art Online II",
    "Sword Art Online: Alicization",
    "Sword Art Online: Alicization - War of Underworld",
    "Sword Art Online Alternative: Gun Gale Online",
    "Accel World",
    "Log Horizon",
    "No Game No Life",
    "No Game No Life: Zero",
    "Re:Zero - Starting Life in Another World",
    "Re:Zero Season 2",
    "Re:Zero Season 3",
    "KonoSuba: God's Blessing on this Wonderful World!",
    "KonoSuba Season 2",
    "KonoSuba Season 3",
    "Overlord",
    "Overlord II",
    "Overlord III",
    "Overlord IV",
    "The Rising of the Shield Hero (Tate no Yuusha)",
    "The Rising of the Shield Hero Season 2",
    "That Time I Got Reincarnated as a Slime (Tensura)",
    "Tensura Season 2",
    "Tensura Season 3",
    "Mushoku Tensei: Jobless Reincarnation",
    "Mushoku Tensei Season 2",
    "The Eminence in Shadow (Kage no Jitsuryokusha)",
    "The Eminence in Shadow Season 2",
    "Cautious Hero: The Hero Is Overpowered but Overly Cautious",
    "Saga of Tanya the Evil (Youjo Senki)",
    "Isekai Quartet",
    "DanMachi (Is It Wrong to Try to Pick Up Girls in a Dungeon?)",
    "DanMachi II",
    "DanMachi III",
    "DanMachi IV",
    "DanMachi V",
    "Sword Oratoria: Is It Wrong to Try to Pick Up Girls in a Dungeon? On the Side",
    "Goblin Slayer",
    "Goblin Slayer II",
    "Grimgar of Fantasy and Ash (Hai to Gensou no Grimgar)",
    "Delicious in Dungeon (Dungeon Meshi)",
    "Frieren: Beyond Journey's End (Sousou no Frieren)",
    "The Faraway Paladin",
    "Campfire Cooking in Another World with My Absurd Skill",
    "Skeleton Knight in Another World",
    "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs",
    "My Next Life as a Villainess: All Routes Lead to Doom!",

    # Ecchi / Harem / Romance
    "High School DxD",
    "High School DxD New",
    "High School DxD BorN",
    "High School DxD Hero",
    "To LOVE-Ru",
    "Motto To LOVE-Ru",
    "To LOVE-Ru Darkness",
    "To LOVE-Ru Darkness 2nd",
    "Rosario + Vampire",
    "Rosario + Vampire Capu2",
    "Sora no Otoshimono (Heaven's Lost Property)",
    "Sora no Otoshimono Forte",
    "Monster Musume no Iru Nichijou",
    "Prison School (Kangoku Gakuen)",
    "Gakusen Toshi Asterisk (The Asterisk War)",
    "Gakusen Toshi Asterisk Season 2",
    "Rakudai Kishi no Cavalry (Chivalry of a Failed Knight)",
    "Trinity Seven",
    "IS: Infinite Stratos",
    "IS: Infinite Stratos 2",
    "Highschool of the Dead",
    "Date A Live",
    "Date A Live II",
    "Date A Live III",
    "Date A Live IV",
    "Date A Live V",
    "Sekirei",
    "Sekirei: Pure Engagement",
    "Freezing",
    "Freezing Vibration",
    "Campione!",
    "Shinmai Maou no Testament (The Testament of Sister New Devil)",
    "Shinmai Maou no Testament BURST",
    "Hundred",
    "Saijaku Muhai no Bahamut (Undefeated Bahamut Chronicle)",
    "Seireitsukai no Blade Dance",
    "Mahouka Koukou no Rettousei (The Irregular at Magic High School)",
    "Strike the Blood",
    "Strike the Blood II",
    "Strike the Blood III",
    "Strike the Blood IV",
    "Nisekoi",
    "Nisekoi:",
    "Kanojo, Okarishimasu (Rent-a-Girlfriend)",
    "The Quintessential Quintuplets (Gotoubun no Hanayome)",
    "The Quintessential Quintuplets ∬",
    "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You",
    "Domestic na Kanojo (Domestic Girlfriend)",
    "Kuzu no Honkai (Scum's Wish)",
    "Shimoneta: A Boring World Where the Concept of Dirty Jokes Doesn't Exist",
    "Why the Hell Are You Here, Teacher!?",
    "Yuuna and the Haunted Hot Springs",
    "We Never Learn: BOKUBEN",
    "Saekano: How to Raise a Boring Girlfriend",

    # Psychological / Thriller / Mystery / Seinen
    "Death Note",
    "Code Geass: Lelouch of the Rebellion",
    "Code Geass: Lelouch of the Rebellion R2",
    "Code Geass: Rozé of the Recapture",
    "Steins;Gate",
    "Steins;Gate 0",
    "Monster",
    "Psycho-Pass",
    "Psycho-Pass 2",
    "Psycho-Pass 3",
    "Erased (Boku dake ga Inai Machi)",
    "Tokyo Ghoul",
    "Tokyo Ghoul √A",
    "Tokyo Ghoul:re",
    "Parasyte: The Maxim (Kiseijuu)",
    "Another",
    "Mirai Nikki (Future Diary)",
    "Deadman Wonderland",
    "Elfen Lied",
    "Higurashi: When They Cry (Higurashi no Naku Koro ni)",
    "Higurashi: When They Cry - Gou",
    "Umineko: When They Cry",
    "Shiki",
    "Shinsekai yori (From the New World)",
    "Serial Experiments Lain",
    "Ergo Proxy",
    "Texhnolyze",
    "Ghost in the Shell: Stand Alone Complex",
    "Ghost in the Shell",
    "Akira",
    "Perfect Blue",
    "Paprika",
    "Terror in Resonance (Zankyou no Terror)",
    "The Promised Neverland (Yakusoku no Neverland)",
    "The Promised Neverland Season 2",
    "Classroom of the Elite (Youkoso Jitsuryoku)",
    "Classroom of the Elite Season 2",
    "Classroom of the Elite Season 3",
    "Tomodachi Game",
    "Kakegurui: Compulsive Gambler",
    "Kakegurui xx",
    "Kaiji: Ultimate Survivor",
    "Akagi",
    "Death Parade",
    "Baccano!",
    "Durarara!!",
    "Durarara!!x2 Shou",
    "Durarara!!x2 Ten",
    "Durarara!!x2 Ketsu",
    "91 Days",
    "Banana Fish",
    "Great Pretender",
    "Black Lagoon",
    "Black Lagoon: The Second Barrage",
    "Jormungand",
    "Gangsta",
    "Hellsing",
    "Hellsing Ultimate",
    "Drifters",
    "Berserk (1997)",
    "Berserk (2016)",
    "Claymore",
    "Vinland Saga",
    "Vinland Saga Season 2",
    "Kingdom",
    "Dororo",
    "Vagabond",
    "Golden Kamuy",
    "Dorohedoro",
    "Choujin X",

    # Mecha & Sci-Fi
    "Neon Genesis Evangelion",
    "The End of Evangelion",
    "Evangelion: 1.0 You Are (Not) Alone",
    "Evangelion: 2.0 You Can (Not) Advance",
    "Evangelion: 3.0 You Can (Not) Redo",
    "Evangelion: 3.0+1.0 Thrice Upon a Time",
    "Tengen Toppa Gurren Lagann",
    "Gurren Lagann: The Lights in the Sky Are Stars",
    "Cowboy Bebop",
    "Trigun",
    "Trigun Stampede",
    "Outlaw Star",
    "Space Dandy",
    "Cyberpunk: Edgerunners",
    "Mobile Suit Gundam",
    "Mobile Suit Gundam Wing",
    "Mobile Suit Gundam SEED",
    "Mobile Suit Gundam 00",
    "Mobile Suit Gundam: Iron-Blooded Orphans",
    "Mobile Suit Gundam: The Witch from Mercury",
    "Eureka Seven",
    "Darling in the FranXX",
    "Aldnoah.Zero",
    "86 Eighty-Six",
    "86 Eighty-Six Part 2",
    "Vivy: Fluorite Eye's Song",
    "Knights of Sidonia",
    "SSSS.Gridman",
    "SSSS.Dynazenon",
    "Promare",

    # Sports
    "Haikyuu!!",
    "Haikyuu!! Second Season",
    "Haikyuu!! Karasuno Koukou vs Shiratorizawa",
    "Haikyuu!! To the Top",
    "Kuroko no Basket (Kuroko's Basketball)",
    "Kuroko no Basket 2nd Season",
    "Kuroko no Basket 3rd Season",
    "Slam Dunk",
    "Blue Lock",
    "Blue Lock Season 2",
    "Aoashi",
    "Hajime no Ippo",
    "Megalo Box",
    "Nomad: Megalo Box 2",
    "Free! - Iwatobi Swim Club",
    "Free! - Eternal Summer",
    "Yuri!!! on Ice",
    "Run with the Wind (Kaze ga Tsuyoku Fuiteiru)",
    "Diamond no Ace (Ace of Diamond)",
    "Ping Pong the Animation",
    "Prince of Tennis",
    "Eyeshield 21",
    "Yowamushi Pedal",

    # Romance / Drama / Slice of Life
    "Toradora!",
    "Clannad",
    "Clannad: After Story",
    "Kanon",
    "Air",
    "Angel Beats!",
    "Charlotte",
    "The Day I Became a God (Kamisama ni Natta Hi)",
    "Plastic Memories",
    "Anohana: The Flower We Saw That Day",
    "Your Lie in April (Shigatsu wa Kimi no Uso)",
    "Violet Evergarden",
    "A Silent Voice (Koe no Katachi)",
    "Your Name (Kimi no Na wa)",
    "Weathering with You (Tenki no Ko)",
    "Suzume (Suzume no Tojimari)",
    "5 Centimeters per Second",
    "I Want to Eat Your Pancreas (Kimi no Suizou wo Tabetai)",
    "Josee, the Tiger and the Fish",
    "Horimiya",
    "Horimiya: The Missing Pieces",
    "Kaguya-sama: Love is War",
    "Kaguya-sama: Love is War Season 2",
    "Kaguya-sama: Love is War - Ultra Romantic",
    "Kaguya-sama: Love is War - The First Kiss That Never Ends",
    "My Dress-Up Darling (Sono Bisque Doll wa Koi wo Suru)",
    "The Dangers in My Heart (Boku no Kokoro no Yabai Yatsu)",
    "Tomo-chan Is a Girl!",
    "Komi Can't Communicate",
    "Teasing Master Takagi-san (Karakai Jouzu no Takagi-san)",
    "Kimi ni Todoke: From Me to You",
    "Fruits Basket (2019)",
    "Fruits Basket Season 2",
    "Fruits Basket: The Final",
    "Nana",
    "Paradise Kiss",
    "Ouran High School Host Club",
    "Kaichou wa Maid-sama!",
    "Special A",
    "Kamisama Kiss (Kamisama Hajimemashita)",
    "Ao Haru Ride (Blue Spring Ride)",
    "Orange",
    "Golden Time",
    "Kokoro Connect",
    "Rascal Does Not Dream of Bunny Girl Senpai (Seishun Buta Yarou)",
    "Rascal Does Not Dream of a Dreaming Girl",
    "Oregairu (My Teen Romantic Comedy SNAFU)",
    "Oregairu Season 2",
    "Oregairu Climax",
    "Hyouka",
    "Love, Chunibyo & Other Delusions! (Chuunibyou demo Koi ga Shitai!)",
    "Tamako Market",
    "K-On!",
    "K-On!!",
    "Bocchi the Rock!",
    "Hibike! Euphonium (Sound! Euphonium)",
    "Beck: Mongolian Chop Squad",
    "Given",
    "Carole & Tuesday",
    "Kids on the Slope (Sakamichi no Apollon)",
    "Ya Boy Kongming! (Paripi Koumei)",
    "Oshi no Ko",
    "Oshi no Ko Season 2",
    "Spy x Family",
    "Spy x Family Season 2",
    "Buddy Daddies",
    "Kotaro Lives Alone",
    "Barakamon",
    "Non Non Biyori",
    "Yuru Camp (Laid-Back Camp)",
    "A Place Further Than the Universe (Sora yori mo Tooi Basho)",
    "Nichijou - My Ordinary Life",
    "Daily Lives of High School Boys (Danshi Koukousei no Nichijou)",
    "Asobi Asobase",
    "Grand Blue Dreaming",
    "GTO: Great Teacher Onizuka",
    "Golden Boy",
    "The Melancholy of Haruhi Suzumiya",
    "Lucky Star",
    "Lucky Star: Original",
    "Bakemonogatari",
    "Nisemonogatari",
    "Nekomonogatari",
    "Monogatari Series: Second Season",
    "Hanamonogatari",
    "Tsukimonogatari",
    "Owarimonogatari",
    "Kizumonogatari",
    "Zoku Owarimonogatari",
    "Sayonara Zetsubou Sensei",
    "Arakawa Under the Bridge",
    "The Tatami Galaxy",
    "Ping Pong the Animation",
    "Keep Your Hands Off Eizouken!",
    "Mob Psycho 100",
    "Mob Psycho 100 II",
    "Mob Psycho 100 III",
    "One Punch Man",
    "One Punch Man Season 2",
    "Kill la Kill",
    "Little Witch Academia",
    "BNA: Brand New Animal",
    "Dungeon Meshi",
    "Made in Abyss",
    "Made in Abyss: The Golden City of the Scorching Sun",
    "Land of the Lustrous (Houseki no Kuni)",
    "To Your Eternity (Fumetsu no Anata e)",
    "Ranking of Kings (Ousama Ranking)",
    "The Apothecary Diaries (Kusuriya no Hitorigoto)",
    "Heavenly Delusion (Tengoku Daimakyou)",
    "Summer Time Rendering"
]

all_unique = sorted(list(base_titles.union(set(extra_anime))))

with open(OUT_PATH, "w", encoding="utf-8") as f:
    json.dump(all_unique, f, ensure_ascii=False, indent=2)

print(f"Total de títulos únicos para Autocomplete: {len(all_unique)}")
